import = [
  "/home/lechi/.config/alacritty/themes/catppuccin-mocha.toml",
  "/home/lechi/.config/alacritty/fonts/iosevka-term-nf.toml",
]

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 3
y = 6

[font]
size = 12

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[scrolling]
history = 0

