[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[font.normal]
family = "IosevkaTerm Nerd Font"

[window]
dynamic_title = false

[window.dimensions]
columns = 100
lines = 26

[window.padding]
x = 3
y = 6

[font]
size = 12

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[scrolling]
history = 0
