import = [
  "/home/lechi/.config/alacritty/themes/catppuccin-mocha.toml",
  "/home/lechi/.config/alacritty/fonts/iosevka-term-nf.toml",
]

[window]
dynamic_title = false

[window.dimensions]
columns = 100
lines = 26

[window.padding]
x = 3
y = 6

[font]
size = 12

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[shell]
program = "/usr/bin/zellij"
args = ["attach", "--create", "main"]

[scrolling]
history = 0

