theme = "catppuccin_mocha"

[editor]
color-modes = true
end-of-line-diagnostics = "hint"
popup-border = "all"
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-s = ":write-all!"
Z = { Q = ":quit!", Z = ":write-quit-all!" }

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[keys.insert]
C-h = "move_char_left"
C-j = "move_visual_line_down"
C-k = "move_visual_line_up"
C-l = "move_char_right"

C-s = [":write-all!", "normal_mode"]
